version: '3.8'

services:
  # API service
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.api
    container_name: microservice-api
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - API_KEY=${API_KEY:-}
      - API_SECRET=${API_SECRET:-}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
    volumes:
      - api-logs:/app/logs
    networks:
      - microservice-network

  # Database service (PostgreSQL)
  postgres:
    image: postgres:latest
    container_name: microservice-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  api-logs:
    driver: local
  postgres-data:
    driver: local
