version: '3.8'

services:
  # API service
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.Discount.API
    container_name: discount-api
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - GITHUB_BINANCE_API_KEY=${GITHUB_BINANCE_API_KEY:-}
      - GITHUB_BINANCE_API_SECRET=${GITHUB_BINANCE_API_SECRET:-}
      - GITHUB_TELEGRAM_BOT_TOKEN=${GITHUB_TELEGRAM_BOT_TOKEN:-}
      - GITHUB_TELEGRAM_CHAT_ID=${GITHUB_TELEGRAM_CHAT_ID:-}
      - GITHUB_OPENAI_API_KEY=${GITHUB_OPENAI_API_KEY:-}
    volumes:
      - api-logs:/app/logs
    networks:
      - discount-api-network

networks:
  discount-api-network:
    driver: bridge

volumes:
  api-logs:
    driver: local
