name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ github.repository }}/api
  DOTNET_VERSION: "8.0.x"

jobs:
  # Job 1: Build and Test
  build-and-test:
    name: Build and Test .NET Solution
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Configure NuGet authentication for GitHub Packages
      - name: Setup NuGet authentication
        run: |
          # First, check if the source exists
          if dotnet nuget list source | grep -q "github"; then
            echo "Updating existing GitHub source..."
            dotnet nuget update source github \
              --username ${{ github.repository_owner }} \
              --password ${{ secrets.GIT_PAT }} \
              --store-password-in-clear-text
          else
            echo "Adding GitHub source..."
            dotnet nuget add source https://nuget.pkg.github.com/tejpaldev/index.json \
              --name github \
              --username ${{ github.repository_owner }} \
              --password ${{ secrets.GIT_PAT }} \
              --store-password-in-clear-text
          fi

          # Verify the NuGet source is configured correctly
          dotnet nuget list source

      - name: Restore dependencies
        run: |
          # Create a temporary NuGet.config with direct token substitution
          cp NuGet.config NuGet.config.template
          sed -i "s/%GITHUB_USERNAME%/${{ github.repository_owner }}/g" NuGet.config
          sed -i "s/%GITHUB_TOKEN%/${{ secrets.GIT_PAT }}/g" NuGet.config

          # Show NuGet.config (without exposing the token)
          cat NuGet.config | grep -v ClearTextPassword

          # Restore packages
          dotnet restore Discount.sln -p:Platform="Any CPU"

          # Restore the original NuGet.config
          mv NuGet.config.template NuGet.config
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}

      - name: Build
        run: dotnet build Discount.sln --no-restore --configuration Release -p:Platform="Any CPU"

      - name: Test
        run: dotnet test Discount.sln --no-build --configuration Release -p:Platform="Any CPU" --verbosity normal

  # Job 2: Prepare Docker Environment
  prepare-docker:
    name: Prepare Docker Environment
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      api_tags: ${{ steps.meta-api.outputs.tags }}
      api_labels: ${{ steps.meta-api.outputs.labels }}
      sha_tag: sha-${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

  # Job 3: Build and Push API Image
  build-api-image:
    name: Build and Push API Image
    needs: prepare-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/docker/Dockerfile.Discount.API
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:sha-${{ github.sha }}
          labels: ${{ needs.prepare-docker.outputs.api_labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DOTNET_VERSION=${{ env.DOTNET_VERSION }}
            GITHUB_USERNAME=${{ github.repository_owner }}
            GITHUB_TOKEN=${{ secrets.GIT_PAT }}

  # Job 4: Prepare API Deployment Files
  prepare-api-deployment:
    name: Prepare API Deployment Files
    needs: [build-api-image]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment directory
        run: mkdir -p deployment/temp

      - name: Create API docker-compose.yml for deployment
        run: |
          cat > deployment/temp/docker-compose.yml << 'EOL'
          services:
            api:
              image: ${API_IMAGE}
              container_name: discount-api
              restart: unless-stopped
              ports:
                - "5002:80"
              environment:
                - ASPNETCORE_ENVIRONMENT=Production
                - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
                - API_KEY=${API_KEY}
                - API_SECRET=${API_SECRET}
                - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
              volumes:
                - api-logs:/app/logs
              networks:
                - discount-api-network
              healthcheck:
                test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health || exit 0"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 10s

          networks:
            discount-api-network:
              driver: bridge

          volumes:
            api-logs:
              driver: local
          EOL

      - name: Create API deployment script
        run: |
          cat > deployment/temp/deploy-api.sh << 'EOL'
          #!/bin/bash
          set -e

          # Set environment variables for docker-compose
          export API_IMAGE="${API_IMAGE}"
          export BINANCE_API_KEY="${BINANCE_API_KEY}"
          export BINANCE_API_SECRET="${BINANCE_API_SECRET}"
          export TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}"
          export TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID}"
          export OPENAI_API_KEY="${OPENAI_API_KEY}"
          export DATABASE_CONNECTION_STRING="${DATABASE_CONNECTION_STRING}"

          # Debug information
          echo "Using API image: ${API_IMAGE}"
          echo "Using GitHub username: ${GITHUB_USERNAME}"

          # Log in to GitHub Container Registry
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin

          # Pull the latest images
          docker-compose pull

          # Start the containers
          docker-compose up -d

          # Clean up old images
          docker image prune -f

          # Set up firewall rules if needed
          if command -v ufw &> /dev/null; then
            echo "Configuring firewall..."
            sudo ufw allow 22/tcp comment 'SSH'
            sudo ufw allow 80/tcp comment 'HTTP'
            sudo ufw allow 443/tcp comment 'HTTPS'
            sudo ufw allow 5002/tcp comment 'Discount API'

            # Enable firewall if not already enabled
            if ! sudo ufw status | grep -q "Status: active"; then
              sudo ufw --force enable
            fi

            echo "Firewall configured."
          fi
          EOL

          chmod +x deployment/temp/deploy-api.sh

      - name: Upload API deployment files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-deployment-files
          path: |
            deployment/temp/docker-compose.yml
            deployment/temp/deploy-api.sh

  # Job 5: Deploy API to Server
  deploy-api-to-server:
    name: Deploy API to Server
    needs: prepare-api-deployment
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download API deployment files
        uses: actions/download-artifact@v4
        with:
          name: api-deployment-files
          path: deployment/temp

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_HOST }} $(ssh-keyscan ${{ secrets.SERVER_HOST }})" >> ~/.ssh/known_hosts

      - name: Make deploy script executable
        run: chmod +x deployment/temp/deploy-api.sh

      - name: Deploy API to server
        env:
          API_IMAGE: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:sha-${{ github.sha }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          # Create deployment directory on server
          ssh $SSH_USER@$SERVER_HOST "mkdir -p ~/discount-api"

          # Copy deployment files to server
          scp deployment/temp/docker-compose.yml $SSH_USER@$SERVER_HOST:~/microservice/
          scp deployment/temp/deploy-api.sh $SSH_USER@$SERVER_HOST:~/microservice/

          # Set environment variables and run deployment script
          ssh $SSH_USER@$SERVER_HOST "cd ~/discount-api && \
            export API_IMAGE='$API_IMAGE' && \
            export BINANCE_API_KEY='$BINANCE_API_KEY' && \
            export BINANCE_API_SECRET='$BINANCE_API_SECRET' && \
            export TELEGRAM_BOT_TOKEN='$TELEGRAM_BOT_TOKEN' && \
            export TELEGRAM_CHAT_ID='$TELEGRAM_CHAT_ID' && \
            export OPENAI_API_KEY='$OPENAI_API_KEY' && \
            export DATABASE_CONNECTION_STRING='$DATABASE_CONNECTION_STRING' && \
            export GITHUB_TOKEN='$GITHUB_TOKEN' && \
            export GITHUB_USERNAME='$GITHUB_USERNAME' && \
            ./deploy-api.sh"

  # Job 6: Verify API Deployment
  verify-api-deployment:
    name: Verify API Deployment
    needs: deploy-api-to-server
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Check API health
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "Waiting for API service to start..."
          sleep 15
          echo "Checking API health..."
          curl -sSf "http://$SERVER_HOST:5002/health" || echo "API health check failed, but continuing..."

          echo "API deployment verification completed."
